name: Salvador's website
description: Strategy, Data Science, and Sustainability
meta_description: "torenunez - strategy | data science | sustainability"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Salvador J Nunez'
